name       : qogir-gtk-theme
version    : 2022.04.29
release    : 4
source     :
    - https://github.com/vinceliuice/Qogir-theme/archive/refs/tags/2022-04-29.tar.gz : 4cbeab82b362fb3ac849009b501112695e7c8a4ae2e6b65d72bac54c3e14703c
homepage   : https://github.com/vinceliuice/Qogir-theme
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - win : desktop.theme
summary    : Qogir is a flat design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell
description: |
    Qogir is a flat design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell based on Arc gtk theme.
patterns   :
    - win : /usr/share/themes/*Win*
builddeps  :
    - sassc
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
    - win :
        - qogir-gtk-theme
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    ./install.sh --tweaks square --name Qogir-Win --dest $installdir/usr/share/themes

    # Delete cinnamon & unity variants and unuseful files.
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity,AUTHORS,COPYING}
