name       : qogir-gtk-theme
version    : 2021.12.25
release    : 3
source     :
    - https://github.com/vinceliuice/Qogir-theme/archive/refs/tags/2021-12-25.tar.gz : fb6b55b88dd6d69814ccd877efc227f3f62c4c73d1cf407bb02d5b93ee345023
homepage   : https://github.com/vinceliuice/Qogir-theme
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - win : desktop.theme
summary    : Qogir is a flat design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell
description: |
    Qogir is a flat design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell based on Arc gtk theme.
patterns   :
    - win : /usr/share/themes/*win*
builddeps  :
    - sassc
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
    - win :
        - qogir-gtk-theme
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    ./install.sh --tweaks square --name Qogir-win --dest $installdir/usr/share/themes

    # Delete cinnamon & unity variants and unuseful files.
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity,AUTHORS,COPYING}
