name       : qogir-gtk-theme
version    : 2021.08.02
release    : 1
source     :
    - https://github.com/vinceliuice/Qogir-theme/archive/refs/tags/2021-08-02.tar.gz : 8eaa45957cc99088ba8ee566b074e9a12fbc74a7cbc4728bd9efc423839e5604
homepage   : https://github.com/vinceliuice/Qogir-theme
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - win : desktop.theme
summary    : Qogir is a flat design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell
description: |
    Qogir is a flat design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell based on Arc gtk theme.
patterns   :
    - win : /usr/share/themes/*win*
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
    - win :
        - qogir-gtk-theme
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --theme standard --dest $installdir/usr/share/themes

    # Delete cinnamon & unity variants and unuseful files.
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity,AUTHORS,COPYING}
