name       : qogir-gtk-theme
version    : 2022.07.17
release    : 5
source     :
    - https://github.com/vinceliuice/Qogir-theme/archive/refs/tags/2022-07-17.tar.gz : cedee13d0b6bc969e206f402e3875212ca936e8843aa3406ada3f68430b70ac9
homepage   : https://github.com/vinceliuice/Qogir-theme
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - win : desktop.theme
summary    : Qogir is a flat design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell
description: |
    Qogir is a flat design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell based on Arc gtk theme.
patterns   :
    - win : /usr/share/themes/*Win*
builddeps  :
    - sassc
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
    - win :
        - qogir-gtk-theme
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    ./install.sh --tweaks square --name Qogir-Win --dest $installdir/usr/share/themes

    # Delete cinnamon & unity variants and unuseful files.
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity,AUTHORS,COPYING}

    # Delete hdpi and xhdpi variants which are only for xfce
    rm -rf $installdir/usr/share/themes/*hdpi*
